public enum Beer {
    MANDRIN_CHARTREUSE,
    KERNEL_IPA,
    ST_BERNARDUS,
    PUNK_IPA,
    LONDON_PORTER,
    MAREDSOUS,
    DUVEL,
    MOINETTE,
    TRIPLE_KARMELIET,
    BLANCHE_DE_BRUXELLES,
    CHIMAY_DOREE,
    MARKUS_BRUNE,
    SAISON_DUPONT_BIO,
    KRO
}
